### ISSUE TITLE
ветка cone

### ISSUE THREAD

**Issue by dumbman** [epicf/ef_python#14]
В файле InnerRegionsManager.py в inite 52 строчка

            elif InnerRegionConeAlongZ.is_cone_region(sec_name):
                new_obj.regions.append(
                    InnerRegionTube.init_from_config(conf,
                                                     conf[sec_name],
                                                     sec_name,
                                                     spat_mesh))

В cone трубка создается получается

**Comment by noooway** [comment]
Да, действительно.
Ошибки copy-paste'а.
Вроде поправил.
