### ISSUE TITLE
Частицы не чувствуют Inner region

### ISSUE THREAD

**Issue by dumbman** [epicf/ef_python#6]
Я сделал пример где сравниваются пучки с электродами и внешним полем. Нашел два недостатка:
1. Пучок пролетает сквозь анод. В первом расчете
2. После запуска ячейки с командой выполнения программы. Она все посчитала. Все h5 файлы есть в папке, но ячейка почему то в работе знак  [*] не исчезает . Приходится останавливать kernel. И продолжать строить графики уже после остановки.

**Comment by noooway** [comment]
Хорошо, буду смотреть. Залей конфиг куда-нибудь.

**Comment by dumbman** [comment]
Так там же юпитер блокнот в папке examples/field_from_file

**Comment by noooway** [comment]
Да, я понял. Просто не заметил вначале.
